#MSSQL Driver
#jdbc.driver=com.sqlserver.jdbc.Driver

#MySQL Driver
jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.driver=com.mysql.jdbc.Driver

#Old Local Server
#jdbc.url=jdbc:mysql://localhost:3306/sims
#jdbc.username=root
#jdbc.password=ONsemi123

#Local Server
#jdbc.url=jdbc:mysql://localhost:3306/simsrl
#jdbc.username=root
#jdbc.password=root

#Production Server
#jdbc.url=jdbc:mysql://localhost:3306/ostorms
<<<<<<< HEAD
jdbc.url=jdbc:mysql://localhost:3306/mib?serverTimezone=UTC&useLegacyDatetimeCode=false
jdbc.username=root
jdbc.password=root

#hims DB
cdars.jdbc.url=jdbc:mysql://mysed-rel-app03:3306/cdars?serverTimezone=UTC&useLegacyDatetimeCode=false
cdars.jdbc.username=root
cdars.jdbc.password=root

#Production Server
#jdbc.url="jdbc:sqlserver://MYSE01WS039\GP01QA;databaseName=MIB_SBN;integratedSecurity=true";
#jdbc.username=root
#jdbc.password=root
=======
jdbc.url=jdbc:mysql://localhost:3306/ostorms?serverTimezone=UTC&useLegacyDatetimeCode=false
jdbc.username=root
jdbc.password=root
>>>>>>> 6efe209c46c7289024abf9bf84bf5b36e7452772

#BoneCP
#Default
jdbc.bonecp.idle_connection_test_period=60
jdbc.bonecp.idle_max_age=240
jdbc.bonecp.max_connections_per_partition=30
jdbc.bonecp.min_connections_per_partition=10
jdbc.bonecp.partition_count=3
jdbc.bonecp.acquire_increment=5
jdbc.bonecp.statements_cache_size=100