# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

#Production Config (latest but need to test)
#ldap.url=adldap.ad.onsemi.com:389/o=ondex
#ldap.userDnPatterns=cn={0},ou=seremban,ou=onsemi

#Production Config (New)
ldap.url=ldap://ldap.onsemi.com:389/o=ondex
ldap.userDnPatterns=cn={0},ou=seremban,ou=onsemi