#Viewer
sptsItemBarcodePdf.(class)=com.onsemi.mib.pdf.viewer.SptsItemBarcodePdf
innerLogPdf.(class)=com.onsemi.mib.pdf.viewer.InnerLogPdf
doListPdf.(class)=com.onsemi.mib.pdf.viewer.DoListPdf
doHWListPdf.(class)=com.onsemi.mib.pdf.viewer.DoHWListPdf
sptsItemMultipleBarcodePdf.(class)=com.onsemi.mib.pdf.viewer.SptsItemMultipleBarcodePdf
barcodeStickerPdf.(class)=com.onsemi.mib.pdf.viewer.BarcodeStickerPdf
rmsBookingDetailPdf.(class)=com.onsemi.mib.pdf.viewer.RmsBookingDetailPdf
#Report