#Viewer
<<<<<<< HEAD
sptsItemBarcodePdf.(class)=com.onsemi.mib.pdf.viewer.SptsItemBarcodePdf
innerLogPdf.(class)=com.onsemi.mib.pdf.viewer.InnerLogPdf
doListPdf.(class)=com.onsemi.mib.pdf.viewer.DoListPdf
doHWListPdf.(class)=com.onsemi.mib.pdf.viewer.DoHWListPdf
sptsItemMultipleBarcodePdf.(class)=com.onsemi.mib.pdf.viewer.SptsItemMultipleBarcodePdf
barcodeStickerPdf.(class)=com.onsemi.mib.pdf.viewer.BarcodeStickerPdf
=======
sptsItemBarcodePdf.(class)=com.onsemi.ostorms.pdf.viewer.SptsItemBarcodePdf
innerLogPdf.(class)=com.onsemi.ostorms.pdf.viewer.InnerLogPdf
doListPdf.(class)=com.onsemi.ostorms.pdf.viewer.DoListPdf
doHWListPdf.(class)=com.onsemi.ostorms.pdf.viewer.DoHWListPdf
sptsItemMultipleBarcodePdf.(class)=com.onsemi.ostorms.pdf.viewer.SptsItemMultipleBarcodePdf
barcodeStickerPdf.(class)=com.onsemi.ostorms.pdf.viewer.BarcodeStickerPdf
>>>>>>> 6efe209c46c7289024abf9bf84bf5b36e7452772
#Report